"""The script accumulator — rule R2, and the reason this project exists.

Every successful tool call appends a snippet here. ``export()`` writes a standalone
``.py`` that a clean interpreter can run with only nibabel/nilearn/numpy installed,
reproducing the final state and printing the same numbers.

The compute functions are inlined verbatim from :mod:`neurochat.kernel` rather than
imported, for two reasons: the exported script must not depend on neurochat being
installed, and inlining the *same source text* the tools ran makes drift between
"what happened" and "what the script says happened" structurally impossible.
"""

from __future__ import annotations

import ast
import datetime as _dt
import inspect
import json
import platform
from dataclasses import dataclass, field
from pathlib import Path

from . import __version__, kernel


def tool_versions() -> dict:
    versions = {"python": platform.python_version(), "neurochat": __version__}
    for module_name in ("numpy", "nibabel", "nilearn", "scipy"):
        try:
            module = __import__(module_name)
            versions[module_name] = getattr(module, "__version__", "unknown")
        except ImportError:
            versions[module_name] = "not installed"
    return versions


def _kernel_source() -> str:
    """The kernel's source, minus its docstring and ``__future__`` import."""
    source = inspect.getsource(kernel)
    lines = source.splitlines()
    module = ast.parse(source)
    if (
        module.body
        and isinstance(module.body[0], ast.Expr)
        and isinstance(getattr(module.body[0], "value", None), ast.Constant)
        and isinstance(module.body[0].value.value, str)
    ):
        lines = lines[module.body[0].end_lineno :]
    lines = [line for line in lines if not line.startswith("from __future__")]
    while lines and not lines[0].strip():
        lines.pop(0)
    return "\n".join(lines).rstrip()


@dataclass
class ScriptStep:
    """One tool call's worth of emitted code."""

    index: int
    tool: str
    code: str
    comment: str = ""
    suggested_only: bool = False  # R3: emitted as a comment, never executed
    timestamp: str = ""

    def render(self) -> str:
        header = f"# --- step {self.index}: {self.tool} " + "-" * max(0, 58 - len(self.tool))
        body = [header]
        if self.comment:
            body.extend(f"# {line}" for line in self.comment.splitlines())
        if self.suggested_only:
            body.append("# NOT RUN — suggested code only, outside neurochat's tool surface:")
            body.extend(f"#   {line}" for line in self.code.splitlines())
        else:
            body.append(self.code.rstrip())
        return "\n".join(body)


@dataclass
class ScriptAccumulator:
    """Live, ordered record of the session as runnable code."""

    session_id: str = "session"
    started_at: str = field(
        default_factory=lambda: _dt.datetime.now(_dt.timezone.utc).isoformat(timespec="seconds")
    )
    steps: list[ScriptStep] = field(default_factory=list)

    def add(self, tool: str, code: str, comment: str = "", suggested_only: bool = False) -> ScriptStep:
        step = ScriptStep(
            index=len(self.steps) + 1,
            tool=tool,
            code=code,
            comment=comment,
            suggested_only=suggested_only,
            timestamp=_dt.datetime.now(_dt.timezone.utc).isoformat(timespec="seconds"),
        )
        self.steps.append(step)
        return step

    def add_suggestion(self, tool: str, code: str, comment: str = "") -> ScriptStep:
        """Record code we are declining to run (R3), so the user can run it themselves."""
        return self.add(tool, code, comment=comment, suggested_only=True)

    # -- rendering -------------------------------------------------------

    def preamble(self, standalone: bool = True) -> str:
        versions = tool_versions()
        version_lines = "\n".join(f"#   {k:<10} {v}" for k, v in versions.items())
        header = f'''#!/usr/bin/env python3
"""Reproducible analysis script generated by neurochat.

Session:    {self.session_id}
Started:    {self.started_at}
Exported:   {_dt.datetime.now(_dt.timezone.utc).isoformat(timespec="seconds")}

Every step below corresponds to one tool call in the conversation that produced it.
Running this file reproduces the final state and prints the same numbers.

Scope note: this script is descriptive exploration only. It contains no statistical
inference, no preprocessing and no clinical interpretation. See the project's
LIMITATIONS.md.
"""

# Recorded environment (a different version may give different numbers):
{version_lines}

import json
from pathlib import Path

import nibabel as nib
import numpy as np
from nilearn import image as nli
from nilearn import plotting


def _out(path):
    """Make sure a derived file's directory exists before writing to it."""
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    return str(path)
'''
        if not standalone:
            return header
        return (
            header
            + "\n"
            + "# " + "=" * 74 + "\n"
            + "# Compute kernel, inlined verbatim from neurochat.kernel so this script\n"
            + "# runs without neurochat installed and cannot drift from what was executed.\n"
            + "# " + "=" * 74 + "\n\n"
            + _kernel_source()
            + "\n\n"
            + "# " + "=" * 74 + "\n"
            + "# Session\n"
            + "# " + "=" * 74 + "\n\n"
            + "RESULTS = {}\n"
            + "VOLUMES = {}\n"
        )

    def render(self, standalone: bool = True) -> str:
        parts = [self.preamble(standalone=standalone)]
        if not self.steps:
            parts.append("# (no tool calls yet)\n")
        for step in self.steps:
            parts.append(step.render() + "\n")
        parts.append(
            "\n# " + "=" * 74 + "\n"
            "# Results, printed so a re-run can be diffed against the session.\n"
            "# " + "=" * 74 + "\n"
            'if __name__ == "__main__":\n'
            "    print(json.dumps(RESULTS, indent=2, sort_keys=True))\n"
        )
        return "\n".join(parts)

    def render_live(self) -> str:
        """What the UI's script pane shows: the steps, without the boilerplate."""
        if not self.steps:
            return "# Your analysis will appear here as you go.\n"
        return "\n\n".join(step.render() for step in self.steps) + "\n"

    def export(self, path: str | Path) -> Path:
        target = Path(path).expanduser().resolve()
        if target.suffix != ".py":
            target = target.with_suffix(".py")
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(self.render())
        target.chmod(0o755)
        return target

    def to_dict(self) -> dict:
        return {
            "session_id": self.session_id,
            "started_at": self.started_at,
            "n_steps": len(self.steps),
            "steps": [
                {
                    "index": s.index,
                    "tool": s.tool,
                    "code": s.code,
                    "suggested_only": s.suggested_only,
                    "timestamp": s.timestamp,
                }
                for s in self.steps
            ],
        }


def py_literal(value) -> str:
    """Render a value as a Python literal for embedding in emitted code."""
    if isinstance(value, Path):
        return repr(str(value))
    if isinstance(value, (list, tuple)):
        return "[" + ", ".join(py_literal(v) for v in value) + "]"
    if isinstance(value, dict):
        return json.dumps(value)
    return repr(value)
